In [4]:
# ! pip install mysql-connector-python
# !pip install recommenders
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

In [5]:
# conn = ps.connect(
#     host=os.environ["db_host"],
#     port=os.environ["db_port"],
#     dbname=os.environ["db_name"],
#     user=os.environ["db_user"],
#     password=os.environ["db_password"])

# df = pd.read_sql_query("select * from <table>", con=conn)

In [6]:
file = 'steam-200k-cleaned.csv'
col = ['playerID', 'gameName', 'Action', 'playHours']
df = pd.read_csv(file, header = None,names = col )
df

         playerID                     gameName    Action  playHours
0        11794760  Zuma's Revenge! - Adventure  purchase        1.0
1        11794760  Zuma's Revenge! - Adventure      play        0.2
2        20772968  Zuma's Revenge! - Adventure  purchase        1.0
3        20772968  Zuma's Revenge! - Adventure      play        1.7
4       110899658               Zuma's Revenge  purchase        1.0
...           ...                          ...       ...        ...
199124   71510748                          140  purchase        1.0
199125  106956838                          140  purchase        1.0
199126   78309377                          140  purchase        1.0
199127  154230723                          140  purchase        1.0
199128  154230723                          140      play        1.5

[199129 rows x 4 columns]

In [7]:
prototypeDf = df[(df['Action'] =="play")]

In [8]:
prototypeDf

         playerID                     gameName Action  playHours
1        11794760  Zuma's Revenge! - Adventure   play        0.2
3        20772968  Zuma's Revenge! - Adventure   play        1.7
5       110899658               Zuma's Revenge   play      126.0
7        12144171               Zuma's Revenge   play        1.2
10       69954842               Zuma's Revenge   play        9.3
...           ...                          ...    ...        ...
199114   21061921                          140   play        0.4
199119  120523185                          140   play        2.0
199121   30246419                          140   play        1.2
199123  130312302                          140   play        1.2
199128  154230723                          140   play        1.5

[70412 rows x 4 columns]

In [9]:
prototypeDf = prototypeDf[prototypeDf['playHours'] >= 0.1]

In [10]:
prototypeDf

         playerID                     gameName Action  playHours
1        11794760  Zuma's Revenge! - Adventure   play        0.2
3        20772968  Zuma's Revenge! - Adventure   play        1.7
5       110899658               Zuma's Revenge   play      126.0
7        12144171               Zuma's Revenge   play        1.2
10       69954842               Zuma's Revenge   play        9.3
...           ...                          ...    ...        ...
199114   21061921                          140   play        0.4
199119  120523185                          140   play        2.0
199121   30246419                          140   play        1.2
199123  130312302                          140   play        1.2
199128  154230723                          140   play        1.5

[70412 rows x 4 columns]

In [11]:
prototypeDf = prototypeDf[prototypeDf.groupby('gameName').playerID.transform(len)>=0]
prototypeDf

         playerID                     gameName Action  playHours
1        11794760  Zuma's Revenge! - Adventure   play        0.2
3        20772968  Zuma's Revenge! - Adventure   play        1.7
5       110899658               Zuma's Revenge   play      126.0
7        12144171               Zuma's Revenge   play        1.2
10       69954842               Zuma's Revenge   play        9.3
...           ...                          ...    ...        ...
199114   21061921                          140   play        0.4
199119  120523185                          140   play        2.0
199121   30246419                          140   play        1.2
199123  130312302                          140   play        1.2
199128  154230723                          140   play        1.5

[70412 rows x 4 columns]

In [12]:
print("Games Number : " + str(prototypeDf['gameName'].nunique()) )

Games Number : 3582

In [13]:
prototypeDf

         playerID                     gameName Action  playHours
1        11794760  Zuma's Revenge! - Adventure   play        0.2
3        20772968  Zuma's Revenge! - Adventure   play        1.7
5       110899658               Zuma's Revenge   play      126.0
7        12144171               Zuma's Revenge   play        1.2
10       69954842               Zuma's Revenge   play        9.3
...           ...                          ...    ...        ...
199114   21061921                          140   play        0.4
199119  120523185                          140   play        2.0
199121   30246419                          140   play        1.2
199123  130312302                          140   play        1.2
199128  154230723                          140   play        1.5

[70412 rows x 4 columns]

playHoursAvgDf : col( gameName	playHours)

In [14]:
# make Avg Table 
playHoursAvgDf = prototypeDf.groupby(['gameName'],as_index = False).playHours.mean()

In [15]:
# playHoursAvgDf['playHours'] is avg now , then new a table playHoursAvgDf
playHoursAvgDf['avg_playHours'] = playHoursAvgDf['playHours']
playHoursAvgDf.drop(columns = 'playHours',inplace = True)
playHoursAvgDf.head()

                                            gameName  avg_playHours
0                                        007 Legends           0.70
1                                          0RBITALIS           0.40
2  1... 2... 3... KICK IT! (Drop That Beat Like a...           4.00
3                                    10 Second Ninja           2.95
4                                         10,000,000           3.60

In [16]:
# let prototypeDf + playHoursAvgDf = FullColDf
FullColDf = prototypeDf.merge(playHoursAvgDf,on='gameName')
FullColDf

        playerID                     gameName Action  playHours  avg_playHours
0       11794760  Zuma's Revenge! - Adventure   play        0.2           0.95
1       20772968  Zuma's Revenge! - Adventure   play        1.7           0.95
2      110899658               Zuma's Revenge   play      126.0          45.50
3       12144171               Zuma's Revenge   play        1.2          45.50
4       69954842               Zuma's Revenge   play        9.3          45.50
...          ...                          ...    ...        ...            ...
70407   21061921                          140   play        0.4           1.26
70408  120523185                          140   play        2.0           1.26
70409   30246419                          140   play        1.2           1.26
70410  130312302                          140   play        1.2           1.26
70411  154230723                          140   play        1.5           1.26

[70412 rows x 5 columns]

In [17]:
RatingCondition = [
    FullColDf['playHours'] >= (1.25*FullColDf['avg_playHours']),# 5
    (FullColDf['playHours'] < (1.25*FullColDf['avg_playHours']))&(FullColDf['playHours'] >= (FullColDf['avg_playHours'])),# 4
    (FullColDf['playHours'] < (FullColDf['avg_playHours']))&(FullColDf['playHours'] >= (0.5*FullColDf['avg_playHours'])),# 3
    (FullColDf['playHours'] < (0.5*FullColDf['avg_playHours']))&(FullColDf['playHours'] >= (0.25*FullColDf['avg_playHours'])),# 2
    (FullColDf['playHours'] >= 0),# 1
]

# 125% = 5
# 124.9% ~100% = 4
# 99.9%~50% = 3
# 50%~25% = 2
# have play rating 1

RatingMark = [5,4,3,2,1]

FullColDf['rating'] = np.select(RatingCondition,RatingMark)

FullColDf

,playerID,gameName,Action,playHours,avg_playHours,rating
0,11794760,Zuma's Revenge! - Adventure,play,0.2,0.95,1
1,20772968,Zuma's Revenge! - Adventure,play,1.7,0.95,5
2,110899658,Zuma's Revenge,play,126.0,45.50,5
3,12144171,Zuma's Revenge,play,1.2,45.50,1
4,69954842,Zuma's Revenge,play,9.3,45.50,1
...,...,...,...,...,...,...
70407,21061921,140,play,0.4,1.26,2
70408,120523185,140,play,2.0,1.26,5
70409,30246419,140,play,1.2,1.26,3
70410,130312302,140,play,1.2,1.26,3
70411,154230723,140,play,1.5,1.26,4

In [18]:
FullColDf.drop(columns = ['Action','playHours','avg_playHours'], inplace = True)
FullColDf

        playerID                     gameName  rating
0       11794760  Zuma's Revenge! - Adventure       1
1       20772968  Zuma's Revenge! - Adventure       5
2      110899658               Zuma's Revenge       5
3       12144171               Zuma's Revenge       1
4       69954842               Zuma's Revenge       1
...          ...                          ...     ...
70407   21061921                          140       2
70408  120523185                          140       5
70409   30246419                          140       3
70410  130312302                          140       3
70411  154230723                          140       4

[70412 rows x 3 columns]

In [19]:
piv_dataFrame=FullColDf.pivot_table(index='playerID', columns='gameName',values="rating").fillna(0)

In [20]:
piv_dataFrame

gameName,007 Legends,0RBITALIS,1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby),10 Second Ninja,"10,000,000",100% Orange Juice,1000 Amps,12 Labours of Hercules,12 Labours of Hercules II The Cretan Bull,12 Labours of Hercules III Girl Power,...,rFactor,rFactor 2,realMyst,realMyst Masterpiece Edition,resident evil 4 / biohazard 4,rymdkapsel,sZone-Online,the static speaks my name,theHunter,theHunter Primal
playerID,,,,,,,,,,,,,,,,,,,,,
5250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76767,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
144736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
181212,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309434439,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309554670,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309626088,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309824202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309903146,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
def standardize(row):
    new_row = (row - row.mean()) / (row.max() - row.min())
    return new_row

piv_dataFrame = piv_dataFrame.apply(standardize)

In [22]:
piv_dataFrame

gameName,007 Legends,0RBITALIS,1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby),10 Second Ninja,"10,000,000",100% Orange Juice,1000 Amps,12 Labours of Hercules,12 Labours of Hercules II The Cretan Bull,12 Labours of Hercules III Girl Power,...,rFactor,rFactor 2,realMyst,realMyst Masterpiece Edition,resident evil 4 / biohazard 4,rymdkapsel,sZone-Online,the static speaks my name,theHunter,theHunter Primal
playerID,,,,,,,,,,,,,,,,,,,,,
5250,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
76767,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
86540,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
144736,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
181212,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309434439,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
309554670,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
309626088,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
309824202,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159
309903146,-0.000088,-0.000194,-0.000282,-0.000106,-0.000088,-0.000335,-0.000088,-0.000441,-0.000388,-0.000194,...,-0.000088,-0.000088,-0.000141,-0.000141,-0.000705,-0.000088,-0.002944,-0.000476,-0.004813,-0.000159

In [23]:
game_similarity = cosine_similarity(piv_dataFrame.T)
print(len(game_similarity))

3582

In [24]:
game_similarity_df = pd.DataFrame(game_similarity,index=piv_dataFrame.columns,columns=piv_dataFrame.columns)

game_similarity_df

gameName,007 Legends,0RBITALIS,1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby),10 Second Ninja,"10,000,000",100% Orange Juice,1000 Amps,12 Labours of Hercules,12 Labours of Hercules II The Cretan Bull,12 Labours of Hercules III Girl Power,...,rFactor,rFactor 2,realMyst,realMyst Masterpiece Edition,resident evil 4 / biohazard 4,rymdkapsel,sZone-Online,the static speaks my name,theHunter,theHunter Primal
gameName,,,,,,,,,,,,,,,,,,,,,
007 Legends,1.000000,-0.000148,-0.000176,-0.000104,-0.000088,-0.000211,-0.000088,-0.000219,-0.000209,-0.000148,...,-0.000088,-0.000088,-0.000129,-0.000121,-0.000298,-0.000088,-0.000602,-0.000239,-0.000831,-0.000143
0RBITALIS,-0.000148,1.000000,-0.000296,0.149391,-0.000148,-0.000354,-0.000148,-0.000368,-0.000351,-0.000248,...,-0.000148,-0.000148,-0.000216,-0.000203,-0.000500,-0.000148,-0.001009,-0.000401,0.030209,-0.000239
1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby),-0.000176,-0.000296,1.000000,-0.000207,-0.000176,-0.000422,-0.000176,-0.000439,-0.000418,-0.000296,...,-0.000176,-0.000176,-0.000258,-0.000242,-0.000596,-0.000176,0.014127,-0.000479,-0.001662,-0.000285
10 Second Ninja,-0.000104,0.149391,-0.000207,1.000000,-0.000104,-0.000248,-0.000104,-0.000258,-0.000246,-0.000174,...,-0.000104,-0.000104,-0.000152,-0.000142,-0.000351,-0.000104,-0.000708,-0.000282,-0.000978,-0.000168
"10,000,000",-0.000088,-0.000148,-0.000176,-0.000104,1.000000,-0.000211,-0.000088,-0.000219,-0.000209,-0.000148,...,-0.000088,-0.000088,-0.000129,-0.000121,-0.000298,-0.000088,-0.000602,-0.000239,-0.000831,-0.000143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rymdkapsel,-0.000088,-0.000148,-0.000176,-0.000104,-0.000088,-0.000211,-0.000088,-0.000219,-0.000209,-0.000148,...,-0.000088,-0.000088,-0.000129,-0.000121,-0.000298,1.000000,-0.000602,-0.000239,-0.000831,-0.000143
sZone-Online,-0.000602,-0.001009,0.014127,-0.000708,-0.000602,-0.001441,-0.000602,-0.001497,-0.001428,-0.001009,...,-0.000602,-0.000602,-0.000879,-0.000826,-0.002035,-0.000602,1.000000,0.060007,0.143959,-0.000973
the static speaks my name,-0.000239,-0.000401,-0.000479,-0.000282,-0.000239,-0.000573,-0.000239,-0.000595,-0.000568,-0.000401,...,-0.000239,-0.000239,-0.000350,-0.000328,-0.000809,-0.000239,0.060007,1.000000,0.025521,-0.000387
theHunter,-0.000831,0.030209,-0.001662,-0.000978,-0.000831,-0.001990,-0.000831,-0.002068,-0.001972,-0.001394,...,-0.000831,-0.000831,-0.001214,-0.001140,0.003030,-0.000831,0.143959,0.025521,1.000000,0.153744
theHunter Primal,-0.000143,-0.000239,-0.000285,-0.000168,-0.000143,-0.000341,-0.000143,-0.000355,-0.000338,-0.000239,...,-0.000143,-0.000143,-0.000208,-0.000196,-0.000482,-0.000143,-0.000973,-0.000387,0.153744,1.000000

In [25]:
def get_similarity_game(game_name,user_rating):

    similarity_mark = game_similarity_df[game_name]*user_rating
    similarity_mark = similarity_mark.sort_values(ascending=False)

    return similarity_mark

print(get_similarity_game("Warframe",5))

gameName
Warframe                 5.000000
Starbound                1.057702
Borderlands 2            1.008411
PlanetSide 2             0.997047
Garry's Mod              0.971719
                           ...
Football Manager 2009   -0.036454
Football Manager 2015   -0.054219
Football Manager 2014   -0.054626
Football Manager 2012   -0.056386
Football Manager 2013   -0.063263
Name: Warframe, Length: 3582, dtype: float64

In [26]:
game_lover = [("Zombies Monsters Robots",5),("Blockstorm",3),("Blocks That Matter",1)]

print(type(game_lover))
print(game_lover)

similarity_games_tb = pd.DataFrame()

for game,rating in game_lover:
    similarity_games_tb = similarity_games_tb.append(get_similarity_game(game,rating),ignore_index=True)


similarity_games_tb.head()

similarity_games_tb.sum().sort_values(ascending = False)

<class 'list'>
[('Zombies Monsters Robots', 5), ('Blockstorm', 3), ('Blocks That Matter', 1)]

Zombies Monsters Robots                 4.995800
Blockstorm                              2.994576
Global Agenda - Beta                    1.615051
Robot Rescue Revolution                 1.615051
The Chaos Engine                        1.615051
                                          ...
Dying Light                            -0.023279
Football Manager 2013                  -0.025575
Call of Duty Black Ops - Multiplayer   -0.030242
Call of Duty Black Ops                 -0.031642
Counter-Strike                         -0.046107
Length: 3582, dtype: float64

In [27]:

# game_lover_mode1=[]
# gameNameList = FullColDf['gameName'].tolist()
# gameNameList = list(dict.fromkeys(gameNameList))
#
# for i in range(5):

  # while True:
#     gameName = input(f"Enter The number or {i+1} gameName: ")
#     if not gameName in gameNameList:
#       print("This game is not in steam.plase enter other game.")
#     else:
#       break
#
#   while True:
#     try:
#         rating = int(input(f"Enter The number or {i+1} rating: (1-5)"))
#     except ValueError:
#         print("Please, enter a valid integer")
#         continue
#     else:
#         if rating >=0 and rating <=5:
#           game_lover_mode1.append([gameName,rating])
#           break
#         else:
#           print("rating only can be 1 to 5")
#
# print("===========================")
# similarity_games_tb = pd.DataFrame( columns=["GameName","RecommendationMark"])
#
# for game,rating in game_lover_mode1:
#     similarity_games_tb = similarity_games_tb.append(get_similarity_game(game,rating),ignore_index=False)
#
# print(type(similarity_games_tb))
#
# # 4
#
# show_td = similarity_games_tb.sum().sort_values(ascending = False)
#
# user_dataFrame = show_td.to_frame()
#
# user_dataFrame.reset_index(inplace=True)
#
# user_dataFrame.rename(columns = {'index':'GameName'}, inplace = True)
#
# # print(game_lover_mode1)
#
# for gameName,rating in game_lover_mode1:
#     user_dataFrame = user_dataFrame[user_dataFrame.GameName != gameName]
#
# user_dataFrame.dropna().reset_index(drop=True)
#
# user_dataFrame.head(10)